Create Issue for Fail Tests

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -33,6 +33,30 @@ jobs:
     - name: Run TDD Test
       uses: robherley/go-test-action@v0.1.0
 
+    # Checking for Failed Tests
+    - name: Extract Failed Tests
+      run: rebot --report none TestCases/output.xml > failed_tests.txt
+
+    - name: Check for failed tests
+      run: |
+        if [[ -f "failed_tests.txt" && $(wc -l < "failed_tests.txt") -gt 0 ]]; then
+          exit 1  # Set exit code to trigger issue creation
+        fi
+        
+    # Create Issue on Fail TDD Tests
+    - name: Create Issue on TDD Test Failure
+      if: ${{ failure() }}
+      uses: dacbd/create-issue-action@main
+      with:
+        token: ${{ github.token }}
+        title: "TDD Fail Tests in ${{ github.workflow }} "
+        body: |
+          **Failed tests have been detected.**
+          $(cat failed_tests.txt)
+          
+          **Please investigate and address the failures.**
+        assignees: ${{ github.actor }}
+
     # Build and run MySQL container and detach
     - name: Start MySQL container
       run: docker run --name mysql_container -d koayyiting/mysql_test:latest
@@ -54,6 +78,30 @@ jobs:
       uses: joonvena/robotframework-docker-action@v1.0
       with:
         robot_tests_dir: TestCases
+
+    # Checking for Failed Tests
+    - name: Extract failed tests
+      run: rebot --report none TestCases/output.xml > failed_tests.txt
+
+    - name: Check for failed tests
+      run: |
+        if [[ -f "failed_tests.txt" && $(wc -l < "failed_tests.txt") -gt 0 ]]; then
+          exit 1  # Set exit code to trigger issue creation
+        fi
+      
+    # Create Issue on Fail BDD Tests
+    - name: Create Issue on BDD Test Failure
+      if: ${{ failure() }}
+      uses: dacbd/create-issue-action@main
+      with:
+        token: ${{ github.token }}
+        title: "BDD Failed Tests in ${{ github.workflow }} "
+        body: |
+          **Failed tests have been detected.**
+          $(cat failed_tests.txt)
+          
+          **Please investigate and address the failures.**
+        assignees: luketeran, ${{ github.actor }}
 
     # Test DB if working2
     - name: Wait for MySQL to start2
